language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
  - git submodule update --init --recursive
install:
  - ./gradlew
script:
  - ./gradlew :app:assembleDebug --stacktrace
  - ./gradlew :app:test --stacktrace
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - wget -O - $KEYSTORE_URL | gpg -d --passphrase $KEYSTORE_PASSPHRASE -o keystore.jks
  - >
    ./gradlew assemble
    -Pandroid.injected.signing.store.file=$PWD/keystore.jks
    -Pandroid.injected.signing.store.password=$STORE_PASSWORD
    -Pandroid.injected.signing.key.alias=$KEY_ALIAS
    -Pandroid.injected.signing.key.password=$KEY_PASSWORD
deploy:
  - file_glob: true
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: app/build/outputs/apk/*/*/app-*.apk
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      tags: false
      condition: $TRAVIS_EVENT_TYPE = api
  - file_glob: true
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: app/build/outputs/apk/*/*/app-*.apk
    skip_cleanup: true
    draft: false
    on:
      tags: true
